# Generated by Django 4.2.1 on 2023-12-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_habitudealimentaire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitudealimentaire',
            name='user',
        ),
    ]
