# Generated by Django 4.2.1 on 2023-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_habitudealimentaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recu',
            field=models.BooleanField(default=False),
        ),
    ]
