# Generated by Django 4.2.1 on 2023-12-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_patient_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.CharField(choices=[('C', 'CHIRURGIEN'), ('CA', 'CARDIOLOGUE'), ('DER', 'DERMATOLOGUE'), ('DEN', 'DENTISTE'), ('O', 'OPHTALMOLOGUE'), ('d', 'dollar')], max_length=100),
        ),
    ]
